SELECT USER_ID, FIRST_NAME, LAST_NAME
FROM project2.Public_Users
WHERE USER_ID NOT IN
(SELECT USER1_ID FROM project2.Public_Friends
UNION
SELECT USER2_ID FROM project2.Public_Friends)
ORDER BY USER_ID;

