SELECT DISTINCT U.USER_ID, U.FIRST_NAME, U.LAST_NAME 
FROM project2.Public_User_Hometown_Cities UH, project2.Public_User_Current_Cities UC, project2.Public_Users U
WHERE UH.USER_ID = UC.USER_ID AND U.USER_ID = UC.USER_ID
AND UH.HOMETOWN_CITY_ID != UC.CURRENT_CITY_ID
ORDER BY U.USER_ID;

"SELECT DISTINCT U.USER_ID, U.FIRST_NAME, U.LAST_NAME FROM" + 
HometownCitiesTable + " UH, " + CurrentCitiesTable + " UC, " + UsersTable + " U " +
"WHERE UH.USER_ID = UC.USER_ID AND U.USER_ID = UC.USER_ID" +
"AND UH.HOMETOWN_CITY_ID != UC.CURRENT_CITY_ID" +
"ORDER BY U.USER_ID"