SELECT USER_ID, FIRST_NAME, LAST_NAME FROM
(
    SELECT * FROM 
    (
        SELECT F1.USER2_ID USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH
        FROM project2.Public_Users U JOIN project2.Public_Friends F1 ON U.USER_ID = F1.USER2_ID
        WHERE F1.USER1_ID = 215
        UNION
        SELECT F2.USER1_ID USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH
        FROM project2.Public_Users U JOIN project2.Public_Friends F2 ON U.USER_ID = F2.USER1_ID
        WHERE F2.USER2_ID = 215
    )
    ORDER BY YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USER_ID DESC
)
WHERE ROWNUM <= 1;

"SELECT USER_ID, FIRST_NAME, LAST_NAME FROM( " +
    "SELECT * FROM( " + 
        "SELECT F1.USER2_ID USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH " + 
        "FROM " + UsersTable + " U JOIN " + FriendsTable + " F1 ON U.USER_ID = F1.USER2_ID " +
        "WHERE F1.USER1_ID = " + userID +
        "UNION" + 
        "SELECT F2.USER1_ID USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH " +
        "FROM " + UsersTable + " U JOIN " + FriendsTable + " F2 ON U.USER_ID = F2.USER1_ID " +
        "WHERE F2.USER2_ID = " + userID +
    ") " + 
    "ORDER BY YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, USER_ID DESC) WHERE ROWNUM <= 1"


SELECT USER_ID, FIRST_NAME, LAST_NAME FROM
(
    SELECT * FROM 
    (
        SELECT F1.USER2_ID USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH
        FROM project2.Public_Users U JOIN project2.Public_Friends F1 ON U.USER_ID = F1.USER2_ID
        WHERE F1.USER1_ID = 215
        UNION
        SELECT F2.USER1_ID USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH
        FROM project2.Public_Users U JOIN project2.Public_Friends F2 ON U.USER_ID = F2.USER1_ID
        WHERE F2.USER2_ID = 215
    )
    ORDER BY YEAR_OF_BIRTH DESC, MONTH_OF_BIRTH DESC, DAY_OF_BIRTH DESC, USER_ID DESC
)
WHERE ROWNUM <= 1;

"SELECT USER_ID, FIRST_NAME, LAST_NAME FROM( " +
    "SELECT * FROM( " + 
        "SELECT F1.USER2_ID USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH " + 
        "FROM " + UsersTable + " U JOIN " + FriendsTable + " F1 ON U.USER_ID = F1.USER2_ID " +
        "WHERE F1.USER1_ID = " + userID +
        "UNION" + 
        "SELECT F2.USER1_ID USER_ID, U.FIRST_NAME, U.LAST_NAME, U.YEAR_OF_BIRTH, U.MONTH_OF_BIRTH, U.DAY_OF_BIRTH " +
        "FROM " + UsersTable + " U JOIN " + FriendsTable + " F2 ON U.USER_ID = F2.USER1_ID " +
        "WHERE F2.USER2_ID = " + userID +
    ") " + 
    "ORDER BY YEAR_OF_BIRTH DESC, MONTH_OF_BIRTH DESC, DAY_OF_BIRTH DESC, USER_ID DESC) WHERE ROWNUM <= 1"