SELECT DISTINCT FIRST_NAME FROM project2.Public_Users
WHERE LENGTH(FIRST_NAME) = 
(SELECT DISTINCT MAX(LENGTH(FIRST_NAME)) AS LEN FROM project2.Public_Users)
ORDER BY FIRST_NAME;

SELECT DISTINCT FIRST_NAME FROM project2.Public_Users
WHERE LENGTH(FIRST_NAME) = 
(SELECT DISTINCT MIN(LENGTH(FIRST_NAME)) AS LEN FROM project2.Public_Users)
ORDER BY FIRST_NAME;

SELECT FIRST_NAME, COUNT(*)
FROM project2.Public_Users
GROUP BY FIRST_NAME HAVING COUNT(*) = 
(SELECT MAX(COUNT(*)) FROM project2.Public_Users GROUP BY FIRST_NAME);