CREATE VIEW share_photo AS 
SELECT U1.USER_ID AS U1_ID, U2.USER_ID AS U2_ID ,count(*) AS CNT
FROM project2.public_Users  U1, project2.public_Users  U2, project2.Public_Tags T1, project2.Public_Tags T2 
WHERE U1.USER_ID = T1.TAG_SUBJECT_ID AND U2.USER_ID = T2.TAG_SUBJECT_ID AND T1.TAG_PHOTO_ID = T2.TAG_PHOTO_ID 
AND U1.USER_ID < U2.USER_ID AND U1.GENDER = U2.GENDER 
AND U1.YEAR_OF_BIRTH IS NOT EXISTS AND U2.YEAR_OF_BIRTH IS NOT EXISTS AND abs(U1.YEAR_OF_BIRTH - U2.YEAR_OF_BIRTH) < = 2
GROUP BY U1.USER_ID, U2.USER_ID ORDER BY CNT DESC, U1_ID, U2_ID;

"CREATE VIEW share_photo AS " + 
"SELECT U1.USER_ID AS U1_ID, U2.USER_ID AS U2_ID ,count(*) AS CNT " + 
"FROM " + UsersTable + " U1, " + UsersTable + " U2, " + TagsTable + " T1, " + TagsTable + " T2 " +
"WHERE U1.USER_ID = T1.TAG_SUBJECT_ID AND U2.USER_ID = T2.TAG_SUBJECT_ID AND T1.TAG_PHOTO_ID = T2.TAG_PHOTO_ID " +  
"AND U1.USER_ID < U2.USER_ID AND U1.GENDER = U2.GENDER " + 
"AND U1.YEAR_OF_BIRTH IS NOT NULL AND U2.YEAR_OF_BIRTH IS NOT NULL AND abs(U1.YEAR_OF_BIRTH - U2.YEAR_OF_BIRTH) <= " + YearDiff +
" GROUP BY U1.USER_ID, U2.USER_ID ORDER BY CNT DESC, U1_ID, U2_ID"



SELECT U1.USER_ID, U1.FIRST_NAME, U1.LAST_NAME, U1.YEAR_OF_BIRTH,
U2.USER_ID, U2.FIRST_NAME, U2.LAST_NAME, U2.YEAR_OF_BIRTH,
P.PHOTO_ID, P.ALBUM_ID, A.ALBUM_NAME, P.PHOTO_LINK
FROM project2.public_Users U1, project2.public_Users U2,  share_photo S, project2.Public_Photos P, project2.Public_Albums A, project2.Public_Tags T1, project2.Public_Tags T2  
WHERE (U1.USER_ID, U2.USER_ID) IN (SELECT S.U1_ID, s.U2_ID FROM share_photo S) 
AND S.U1_ID = U1.USER_ID AND S.U2_ID = U2.USER_ID 
AND U1.USER_ID = T1.TAG_SUBJECT_ID AND U2.USER_ID = T2.TAG_SUBJECT_ID AND T1.tag_PHOTO_ID = T2.tag_PHOTO_ID 
AND NOT EXISTS( SELECT F.USER1_ID ,F.USER2_ID FROM project2.Public_Friends F WHERE U1.USER_ID = F.USER1_ID AND U2.USER_ID = F.USER2_ID) 
AND T1.tag_PHOTO_ID = P.PHOTO_ID AND P.ALBUM_ID = A.ALBUM_ID AND rownum <= 5
ORDER BY s.cont DESC ,U1.USER_ID ASC,  U2.USER_ID ASC;

"SELECT U1.USER_ID, U1.FIRST_NAME, U1.LAST_NAME, U1.YEAR_OF_BIRTH, " + 
"U2.USER_ID, U2.FIRST_NAME, U2.LAST_NAME, U2.YEAR_OF_BIRTH, " +
"P.PHOTO_ID, P.ALBUM_ID, A.ALBUM_NAME, P.PHOTO_LINK " +
"FROM " + UsersTable + " U1, " + UsersTable + " U2, share_photo S, " +
PhotosTable + " P, " + AlbumsTable + " A," + TagsTable + " T1, " + TagsTable + " T2 " +  
"WHERE (U1.USER_ID, U2.USER_ID) IN (SELECT S.U1_ID, s.U2_ID FROM share_photo S) " + 
"AND S.U1_ID = U1.USER_ID AND S.U2_ID = U2.USER_ID " +
"AND U1.USER_ID = T1.TAG_SUBJECT_ID AND U2.USER_ID = T2.TAG_SUBJECT_ID AND T1.tag_PHOTO_ID = T2.tag_PHOTO_ID " +
"AND NOT EXISTS (SELECT F.USER1_ID , F.USER2_ID FROM " + FriendsTable + " F WHERE U1.USER_ID = F.USER1_ID AND U2.USER_ID = F.USER2_ID) " +
"AND T1.tag_PHOTO_ID = P.PHOTO_ID AND P.ALBUM_ID = A.ALBUM_ID AND rownum <= " + num +
" ORDER BY S.CNY DESC ,U1.USER_ID ASC,  U2.USER_ID ASC"