SELECT LEAST(U1.USER_ID, U2.USER_ID) AS USER_ID_1,
       GREATEST(U1.USER_ID, U2.USER_ID) AS USER_ID_2,
       U1.FIRST_NAME AS FIRST_NAME_1,
       U1.LAST_NAME AS LAST_NAME_1,
       U2.FIRST_NAME AS FIRST_NAME_2,
       U2.LAST_NAME AS LAST_NAME_2
FROM project2.Public_Users U1
JOIN project2.Public_Users U2 ON U1.LAST_NAME = U2.LAST_NAME 
    AND ABS(U1.YEAR_OF_BIRTH - U2.YEAR_OF_BIRTH) < 10
    AND U1.USER_ID < U2.USER_ID
JOIN project2.Public_Friends F ON (F.USER1_ID = U1.USER_ID AND F.USER2_ID = U2.USER_ID)
JOIN project2.Public_User_Hometown_Cities H1 ON U1.USER_ID = H1.USER_ID
JOIN project2.Public_User_Hometown_Cities H2 ON U2.USER_ID = H2.USER_ID
WHERE H1.HOMETOWN_CITY_ID = H2.HOMETOWN_CITY_ID
ORDER BY USER_ID_1, USER_ID_2;


"SELECT LEAST(U1.USER_ID, U2.USER_ID) AS USER_ID_1, " +
       "GREATEST(U1.USER_ID, U2.USER_ID) AS USER_ID_2, " +
       "U1.FIRST_NAME AS FIRST_NAME_1, " +
       "U1.LAST_NAME AS LAST_NAME_1, " +
       "U2.FIRST_NAME AS FIRST_NAME_2, " +
       "U2.LAST_NAME AS LAST_NAME_2 " +
"FROM " + UsersTable + " U1 " +
"JOIN " + UsersTable + " U2 ON U1.LAST_NAME = U2.LAST_NAME " +
    "AND ABS(U1.YEAR_OF_BIRTH - U2.YEAR_OF_BIRTH) < 10 " +
    "AND U1.USER_ID < U2.USER_ID " +
"JOIN " + FriendsTable + " F ON (F.USER1_ID = U1.USER_ID AND F.USER2_ID = U2.USER_ID) " +
"JOIN " + HometownCitiesTable + " H1 ON U1.USER_ID = H1.USER_ID " +
"JOIN " + HometownCitiesTable + "H2 ON U2.USER_ID = H2.USER_ID " +
"WHERE H1.HOMETOWN_CITY_ID = H2.HOMETOWN_CITY_ID" +
"ORDER BY USER_ID_1, USER_ID_2"

